server:
  port: 8787

spring:
  application:
    name: Request solver
  datasource:
    url: jdbc:postgresql://localhost/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}